id: I2D9318A7
legacy_id: P004425
ocr_import_info:
  bdrc_scan_id: W2PD19446
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T23:34:48'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T10:38:28.616246+00:00'
last_modified: 2022-09-03 18:40:32.094643
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19446
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19446
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་ཡུལ་སྔ་འགྱུར་མཐོ་སློབ་མདོ་སྔགས་ཐོས་བསམ་དར་རྒྱས་གླིང་གི་ལོ་རིམ་དགུའི་སློབ་ཚན།
statistics:
  ocr_word_mean_confidence_index: 0.8313306715415191
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I2PD19448:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19448
      total_pages: 684
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD19448.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9141432019232134
    legacy_id: v001
  I2PD19451:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19451
      total_pages: 934
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2PD19451.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8986631270285552
    legacy_id: v004
  I2PD19450:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19450
      total_pages: 862
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD19450.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7809428649056355
    legacy_id: v003
  I2PD19449:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19449
      total_pages: 604
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD19449.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7937981673227791
    legacy_id: v002
  I2PD19453:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19453
      total_pages: 648
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2PD19453.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8704667051021264
    legacy_id: v006
  I2PD19454:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19454
      total_pages: 444
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2PD19454.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.785011832464006
    legacy_id: v007
  I2PD19452:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19452
      total_pages: 574
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2PD19452.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8177802846887212
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
